development:
  adapter: postgresql
  encoding: utf8
  database: houston_development
  host: localhost
  prepared_statements: false

test:
  adapter: postgresql
  encoding: utf8
  database: houston_test
  host: localhost
  prepared_statements: false

# Just so we can precompile assets locally
production:
  adapter: postgresql
  encoding: utf8
  database: houston_development
  host: localhost
  prepared_statements: false
